url: "https://bridgetown.cards" # the base hostname & protocol for your site, e.g. https://example.com
permalink: pretty
timezone: America/Los_Angeles

collections:
  cards:
    output: true
    sort_by: date
    sort_direction: descending